definitions:
  model.ActivityGroupRequest:
    properties:
      email:
        type: string
      title:
        type: string
    type: object
  model.ActivityGroupResponse:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  model.WebResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact:
    email: uloydev@gmail.com
    name: uloydev
  description: todo list api golang
  title: TODO LIST API
  version: "1.0"
paths:
  /activity-groups:
    get:
      consumes:
      - application/json
      description: get all ActivityGroup data from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.ActivityGroupResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Get All ActivityGroup
      tags:
      - activity-groups
    post:
      consumes:
      - application/json
      description: Create New ActivityGroup / Register ActivityGroup
      parameters:
      - description: Register ActivityGroup
        in: body
        name: ActivityGroup
        required: true
        schema:
          $ref: '#/definitions/model.ActivityGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.ActivityGroupResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Create ActivityGroup
      tags:
      - activity-groups
  /activity-groups/:
    get:
      consumes:
      - application/json
      description: get ActivityGroup data by id from database
      parameters:
      - description: int valid
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.ActivityGroupResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Get ActivityGroup by id
      tags:
      - activity-groups
  /v1/activity-groups/{id}:
    delete:
      consumes:
      - application/json
      description: Delete ActivityGroup
      parameters:
      - description: int valid
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.WebResponse'
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Delete ActivityGroup
      tags:
      - activity-groups
    put:
      consumes:
      - application/json
      description: Update ActivityGroup
      parameters:
      - description: int valid
        in: path
        name: id
        type: integer
      - description: Update ActivityGroup
        in: body
        name: activity-groups
        required: true
        schema:
          $ref: '#/definitions/model.ActivityGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.ActivityGroupResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Update ActivityGroup
      tags:
      - activity-groups
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
